### ISSUE TITLE
Improve error message returned in the interface

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/nerd#1]
The error message is currently returning "Error encountered while requesting the server." which is confusing (as the server is fine) when the problem is the input. 

The error message should be at least say whether the problem is the system, the input data or some 3rd party services (if applicable). 

<img width="1149" alt="screen shot 2016-11-23 at 11 02 01" src="https://cloud.githubusercontent.com/assets/15426/20557577/4c117fae-b16c-11e6-9884-09f9ee64b133.png">

**Comment by lfoppiano** [comment]
This should provide error messages when an error occurs. 

![screen shot 2018-01-10 at 15 06 03](https://user-images.githubusercontent.com/15426/34776639-da2b6570-f617-11e7-8152-d8a61b1d4fce.png)
![screen shot 2018-01-10 at 15 05 50](https://user-images.githubusercontent.com/15426/34776640-da4a6b1e-f617-11e7-8c4c-ae473bfcf9e4.png)
![screen shot 2018-01-10 at 15 05 38](https://user-images.githubusercontent.com/15426/34776641-da666ecc-f617-11e7-9c09-666dc03ba9ec.png)

**Comment by tantikristanti** [comment]
The test for the error messages according to the error occur was done as follows:
1. Test case for Language identification
<img width="443" alt="screen shot 2018-01-17 at 14 39 50" src="https://user-images.githubusercontent.com/28044697/35045503-4fc95810-fb94-11e7-94d4-7551c632c76b.png">

- Result: **Pass**
2. Sentence segmentation
<img width="450" alt="screen shot 2018-01-17 at 15 01 45" src="https://user-images.githubusercontent.com/28044697/35046470-601f1026-fb97-11e7-9d25-04347cd8a0f3.png">

- Result: **Pass**
3. Disambiguation of text
<img width="428" alt="screen shot 2018-01-17 at 15 05 58" src="https://user-images.githubusercontent.com/28044697/35046670-f465061e-fb97-11e7-8a14-cb2b3d018a74.png">

- Result: **Pass**

4. Disambiguation of Pdf files 
<img width="442" alt="screen shot 2018-01-17 at 15 11 12" src="https://user-images.githubusercontent.com/28044697/35046943-c39b21a2-fb98-11e7-82c3-3670e83f6e24.png">

- Result: **Pass**

5. Test case for Concept look-up
a. Test for invalid identifier
<img width="457" alt="screen shot 2018-01-17 at 14 28 58" src="https://user-images.githubusercontent.com/28044697/35045029-ccc3dc66-fb92-11e7-9ef7-7af2375585e6.png">

- Result: **Pass**

b. Test for not found a Wikidata Id (it means that the Wikidata Id does not exist)
<img width="492" alt="screen shot 2018-01-17 at 14 30 09" src="https://user-images.githubusercontent.com/28044697/35045075-f227aa64-fb92-11e7-9d4c-7e761ec3ff80.png">

- Result: **Pass**

c. Test for invalid format of Wikidata Id
<img width="363" alt="screen shot 2018-01-17 at 14 35 39" src="https://user-images.githubusercontent.com/28044697/35045312-b7874260-fb93-11e7-8ffd-a5dca728fb2b.png">

- Result: **Pass**

**Comment by tantikristanti** [comment]
This issue is closed due to the requirements are met and the test cases are passed.
