### ISSUE TITLE
Nerd with Port 8080

### ISSUE THREAD

**Issue by karthinuk107** [kermitt2/nerd#26]
Hi,

How do i start nerd with specific port

I have entity fishing running on port number 8090

**Comment by karthinuk107** [comment]
How to start Nerd web interface which is running on port no 8080?

**Comment by karthinuk107** [comment]
I am referring the documentation.

The console is available at the root address of the server (e.g. for Tomcat at http://<server instance name>/<root context name>, or http://localhost:8080 for jetty deployed instance).

**Comment by lfoppiano** [comment]
Hi @karthinuk107 there is a small mistake in the documentation, please use the port that is available (8090). If you want to change, you can do it from the `pom.xml`.

**Comment by karthinuk107** [comment]
Thank you Foppiano,
and one more thing like, in entity fishing console I don't have NERD text option which annotate long paragraphs.

Sorry for being stupid, I am curious to see the Front-End part which highlighted on Documentation.
Like annotation and right hand side info

**Comment by lfoppiano** [comment]
@karthinuk107 what are you trying to achieve? 
If you like to see some examples there are such in the web demo, on the right side panel. 

To annotate long paragraph you have to do it in your client, in your input, do you have the _definition_ of paragraph (you get them from xml or html) or not?

If you have only long text, you can try an approach as this prototype: https://github.com/lfoppiano/grobid-py-utils/blob/master/python/client/NerdClient.py 

Regards
Luca
