### ISSUE TITLE
Adapt IITB corpus format

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/nerd#37]
currently in branch 0.0.3 -> the iitb corpus is not exactly in the same format as the other corpus, and the evaluation is not working on it. Annotations are given without distinguishing the document where they occur, while this is required in the current evaluation. 
A bit of XML massage on the file iitb.xml is required :)

**Comment by tantikristanti** [comment]
The formatting of the 'iitb.xml' file is handled by the class 'IITBCorpusConverter.java'.
