### ISSUE TITLE
Language recognition in evaluation process with NEDCorpusEvaluation class

### ISSUE THREAD

**Issue by tantikristanti** [kermitt2/nerd#43]
With the current version, the evaluation with NEDCorpusEvaluation class only possible with English language. In order to do the evaluation with several languages, it is needed the process of language recognition as a prerequisite prior to the evaluation step.

**Comment by lfoppiano** [comment]
If the language is specified in the filename of the txt file is better to take it from there first.

**Comment by lfoppiano** [comment]
working fine
