### ISSUE TITLE
Different result of domains for Italian text disambiguation process between 'localhost' and 'nerd.huma-num.fr/test/'

### ISSUE THREAD

**Issue by tantikristanti** [kermitt2/nerd#48]
In order to do the test of new language, Italian, the source of test from the link of 'http://nerd.huma-num.fr/test/' and also from the localhost are provided. Several tests are done to see the result given from both of them. With the test of disambiguation, it's found the fact that the domains given by certain mentions are different. For instance, the mention 'fiori' in 'http://nerd.huma-num.fr/test/' has the domains 'Agriculture, Plants', while in the localhost has the domain 'Plants'.

It should be re-checked the way of calculation in order to get the domains since they are treated differently.

**Comment by tantikristanti** [comment]
[Italian Example1.pdf](https://github.com/kermitt2/nerd/files/1623120/Italian.Example1.pdf)

**Comment by lfoppiano** [comment]
[Educación basada en competencias en línea Lecciones de EE.UU. para América Latina.pdf](https://github.com/kermitt2/nerd/files/1623148/Educacion.basada.en.competencias.en.linea.Lecciones.de.EE.UU.para.America.Latina.pdf)

**Comment by lfoppiano** [comment]
[Minerva-2009-22-retorica-renacimiento.pdf](https://github.com/kermitt2/nerd/files/1623150/Minerva-2009-22-retorica-renacimiento.pdf)

**Comment by lfoppiano** [comment]
Italian article example: 
[2009 Infiniti.pdf](https://github.com/kermitt2/nerd/files/1623153/2009.Infiniti.pdf)

**Comment by lfoppiano** [comment]
Italian article example: 
[Bodria_Berruto.pdf](https://github.com/kermitt2/nerd/files/1623167/Bodria_Berruto.pdf)

**Comment by lfoppiano** [comment]
I cannot get this issue anymore, I'm going to close the issue and if it's happearing again we reopen it.
