### ISSUE TITLE
Different result or NO result at all got for PDF disambiguation from localhost and 'nerd.huma-num.fr/test/'

### ISSUE THREAD

**Issue by tantikristanti** [kermitt2/nerd#49]
When the test is done for the PDF disambiguation, there are different result given both from localhost and 'nerd.huma-num.fr/test/'. These different results appeared for the English and French languages. Meanwhile, for the Italian and Spanish language, the service didn't give anything as results.

**Comment by lfoppiano** [comment]
it was a stupid bug introduced by me :-D should be solved now :-)
