### ISSUE TITLE
Entities with many wikidata statements are creating a huge infobox which mess up the whole visualisation 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/nerd#68]
Example: 

<img width="1236" alt="screen shot 2018-03-01 at 15 54 51" src="https://user-images.githubusercontent.com/15426/36851173-eab6abde-1d68-11e8-9fd6-0224b2aad93b.png">
<img width="1154" alt="screen shot 2018-03-01 at 15 54 38" src="https://user-images.githubusercontent.com/15426/36851191-f57771a2-1d68-11e8-8b03-d9492bd1f67b.png">

**Comment by kermitt2** [comment]
This is already open with task in #38
