### ISSUE TITLE
Acronyms synchronisation with LayoutTokens

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/nerd#69]
There are few glitches with acronyms, when propagated in the whole text 
 - they are not synchronised with LayoutTokens (since the propagation is done on the reconstructed string - the layout token matching is lost) 
 - they have no coordinate position and, in some cases, 
 - the offsets are not matching the correct position, when the stream of text comes from a sub-section of a recognised part of pdf (same issue for wikipedia matches #67)

**Comment by lfoppiano** [comment]
I'm adding the document used for testing: 
[su2015relationship.pdf](https://github.com/kermitt2/nerd/files/1808057/su2015relationship.pdf)

**Comment by tantikristanti** [comment]
Another file to be tested
[TestNerd3.pdf](https://github.com/kermitt2/nerd/files/1810402/TestNerd3.pdf)

**Comment by lfoppiano** [comment]
[1-s2.0-S0031320307001409-main.pdf](https://github.com/kermitt2/nerd/files/1811819/1-s2.0-S0031320307001409-main.pdf)

**Comment by tantikristanti** [comment]
Other articles for testing this issue
[ADSLSystemEnglish.pdf](https://github.com/kermitt2/nerd/files/1824643/ADSLSystemEnglish.pdf)
[SEOGoogleFrancais.pdf](https://github.com/kermitt2/nerd/files/1824644/SEOGoogleFrancais.pdf)

**Comment by tantikristanti** [comment]
This issue is closed after correcting some bugs in propagateAcronym method and after passing several unit tests.
